# -*- coding: utf-8 -*-
"""Lab 1 SP23-BCS-048.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f1EMoRRgIzwj1OS-S0OcB6zS6qfdSKgX
"""

#binary,octal and hexadecimal representation
print(0b10)
print(0o10)
print(0x10)

#Data Types
3
3.5
'hello'
print(type(3))
print(type(3.5))
print(type('hello'))
2+3j
type(2+3j)

"""#Activity 1"""

n=input('enter a number')
if int(n) % 2==0:
  print("even")
else:
  print('odd')

"""#Activity 2"""

# activity 2
summ=0
n=int(input('enter an integer'))
while n!=0:
  summ=summ+n
  n=int(input('enter an integer'))
print("sum of given values is: ",summ)

"""# Activity 3"""

isPrime = True
i=2
n=int(input('enter number '))
while i<n:
  remainder=n%i
  if remainder==0:
    isPrime=False
    break
  else:
    i=i+1
if isPrime:
  print('number is prime')
else:
  print('number is not prime')

"""#Activity 4"""

summ=0
i=0
while i<=4:
  n=int(input('enter number'))
  summ=summ+n
  i=i+1
print('sum is',summ)

"""# Activity 5"""

#calculating sum from 0-10 without loop
n=int(input('enter number '))
print('sum {}'.format(n*(n+1)/2))

"""#Activity 6"""

name = input('what is your name? ')
print('Hello ',name)

job = input('what is your job? ')
print('your job is ',job)

num = input('give me a number ')
print('you said ',num)

"""#Activity 7"""

import random
# Awroken
MINIMUM = 1
MAXIMUM = 9
NUMBER = random.randint(MINIMUM, MAXIMUM)
GUESS = None
ANOTHER = None
TRY = 0
RUNNING = True
print ("Alright...")
while RUNNING:
 GUESS = input("What is your lucky number? ")
 if int(GUESS) < NUMBER:
  print ("Wrong, too low.")
 elif int(GUESS) > NUMBER:
  print ("Wrong, too high.")
 elif GUESS.lower() == "exit":
  print ("Better luck next time.")
 elif int(GUESS) == NUMBER:
  print ("Yes, that's the one, %s." % str(NUMBER))
  if TRY < 2:
    print( "Impressive, only %s tries." % str(TRY))
  elif TRY > 2 and TRY < 10:
    print ("Pretty good, %s tries." % str(TRY))
  else:
    print ("Bad, %s tries." % str(TRY))
  RUNNING = False
 TRY += 1

"""#Lab Task 1"""

num = int(input("Enter an integer: "))
stack = list(str(num))

rev_str = ""
while stack:
    rev_str += stack.pop()

rev = int(rev_str)
print("Reversed number:", rev)

"""#Lab Task 2"""

nums = list(map(int, input("Enter integers separated by spaces: ").split()))

even_sum = 0
odd_sum = 0

for num in nums:
    if num % 2 == 0:
        even_sum += num
    else:
        odd_sum += num

print("Sum of even numbers:", even_sum)
print("Sum of odd numbers:", odd_sum)

"""#Lab Task 3"""

num_terms = int(input("Enter the number of terms: "))

a, b = 0, 1

for _ in range(num_terms):
    print(a, end=" ")
    a, b = b, a + b

"""#Lab Task 4"""

marks = int(input("Enter marks (1-100): "))

if marks < 50:
    grade = "F"
elif 50 <= marks <= 60:
    grade = "E"
elif 61 <= marks <= 70:
    grade = "D"
elif 71 <= marks <= 80:
    grade = "C"
elif 81 <= marks <= 90:
    grade = "B"
elif 91 <= marks <= 100:
    grade = "A"
else:
    grade = "Invalid marks! Please enter a number between 1 and 100."

print("Grade:", grade)

"""#Lab Task 5"""

num = int(input("Enter a number: "))

factorial = 1
for i in range(1, num + 1):
    factorial *= i

print("Factorial of", num, "is", factorial)